<?php

return [
    'RESPONSE_CONSTANTS' => [
        'STATUS_ERROR'   => false,
        'STATUS_SUCCESS' => true,
        'STATUS_OTHER_ERROR'          => 2,
        'STATUS_ACCOUNT_UNAUTHORIZED' => 3,
        'STATUS_ACCOUNT_SUSPENDED'  => 4,
        'STATUS_ACCOUNT_DELETED'    => 5,
        'STATUS_INVALID_TOKEN'      => 6,
        'STATUS_INVALID_USER_TYPE'  => 7,
        'STATUS_EMAIL_NOT_VERIFIED' => 8,
        'INVALID_PARAMETERS_CODE'   => 422,
        'INVALID_PARAMETERS'        => 'Invalid Request Parameters.',
        'UNVERIFIED_USER'           => 'User Not Verified',
        'VERIFIED_USER'             => 'User Has been Verified',
        'CHALLENGE_LIST'            => 'All Challenges',
        'CHALLENGE_ADDED'           => 'Challenge Created Successfully',
        'OTP_SEND'                  => 'Otp has been sent',
        'PROFILE_UPDATED'           => 'Profile Updated',
        'ERROR_BOTH_NOT_ALLOW'      => 'You can only use Email or Phone',
        'PASSWORD_UPDATED'          => 'Password Updated',
        'WRONG_PASSWORD'            => 'Wrong Old Password',
        'RECORD_UPDATE'             => 'Record Update Successfully',
        'GAME_LIST_MSG'             => 'All Games',
        'DAYS_LIST_MSG'             => 'All Days',
        'TEAMS_LIST_MSG'            => 'All Teams',
        'CHALLENGE_LIST_MSG'        => 'All Challenges',
        'PENDING_CHALLENGE_LIST'    => 'All Pending Challenges',
        'REJECTED_CHALLENGE_LIST'   => 'All Rejected Challenges',
        'MESSAGE_SEND_SUCCESSFULLY' => 'Message Send Successfully',
        'MATCH_LIST_MSG'            => 'All Matches',
        'MY_MATCH_LIST_MSG'         => 'My Matches',
        'MATCH_ADDED'               => 'Match Created Successfully',
        'IMAGE_UPLOADED'            => 'Image Uploaded',
        'PASSWORD_SEND'             => 'Password Sent to you',
        'USER_NOT_EXIST'            => 'User Not Exist',
        'TEAM_NOT_EXIST'            => 'Team Not Exist',
        'TEAM_ALREADY_EXIST'        => 'Your Team Already Exist',
        'FEEDBACK_SEND'             => 'Your Feedback Received',
        'TEAM_NOT_FOUND'            => 'Team Not Found',
        'TEAM_ADDED'                => 'Team Added Successfully',
        'TEAM_UPDATED'              => 'Team Updated Successfully',
        'TEAM_MEMBERS_UPDATED'      => 'Team Members Updated Successfully',
        'LOGGED_OUT'                => 'Logout Successfully',
        'VERIFY_YOUR_ACCOUNT'       => 'Kindly Verify your Account',
        'USER_NOT_LOGGED_IN'        => 'User Not Logged In',
        'NOTIFICATION_DELETE'       => 'Notifications Deleted Successfully',
        'TEAM_AVAILABILITY_UPDATED' => 'Team Availability Updated',
        'TEAM_NOTIFICATION_UPDATED' => 'Team Notification Status Updated',
        'RESPONSE_CODE_SUCCESS'     => 200,
        'RESPONSE_CODE_NOT_FOUND'   => 404,
        'RESPONSE_CODE_INVALID_CREDENTIALS'   => 401,
        'RESPONSE_CODE_NOT_ALLOWED' => 405,
        'SIGN_UP_SUCCESS_MESSAGE'   => 'User Sign up successful!',
        'WRONG_OTP'                 => 'Otp mismatch',
        'ERROR_EMAIL_EXIST' => 'Email Already In Use.',
        'ERROR_PHONE_EXIST' => 'Phone Already In Use.',
        'ERROR_USER_NAME_EXIST'      => 'Username Already In Use.',
        'ERROR_INVALID_CREDENTIALS'  => 'Invalid Credentials.',
        'ERROR_ACCOUNT_SUSPENDED'    => 'Your Account Has Been Suspended.',
        'ERROR_ACCOUNT_DELETED'      => 'Your Account Has Been Deleted.',
        'ERROR_ACCOUNT_UNAUTHORIZED' => 'Your Account Is Not Authorized Yet.',
        'ERROR_INVALID_EMAIL'        => 'Invalid Email Address.',
        'ERROR_INVALID_USER_TYPE'    => 'Invalid User Type.',
        'MSG_LOGGED_IN' => 'Logged In Successful!',
        'MSG_LOGGED_OUT'=> 'Logged Out',
        'MSG_REGISTERED_SUCCESS'  => 'Account Registered',
        'MSG_REGISTERED_OPERATOR' => 'Check your email and click on the link to verify',
        'MSG_REGISTERED_CUSTOMER' => 'Activation code sent. Check your email to verify your account.',
        'MSG_DATA_SAVE'   => 'Data has been saved successfully!',
        'MSG_DATA_UPDATE' => 'Data has been updated successfully!',
        'MSG_NOT_FOUND'   => 'Required resource is not found!',
        'MSG_FOUND'       => 'Record Found',
    ],

    //---------Constants for authorization/login
    'AUTH_CONSTANTS' => [
        'KEY_EMAIL'     =>  'email',
        'KEY_PASSWORD'  =>  'password',
    ],

    'otp' => [
        'MESSAGE' => 'Dear User, Your One Time Password for '.env('APP_NAME').'.com is: ',
    ],

    //--------User constants
    'USER_CONSTANTS' => [
        'KEY_USER_ID'          =>  'id',
        'KEY_USER_USERNAME'    =>  'username',
        'KEY_USER_EMAIL'       =>  'email',
        'KEY_USER_PHONE'       =>  'phone',
        'KEY_USER_DEVICE_ID'   =>  'device_id',
        'KEY_USER_DEVICE_TYPE' =>  'device_type',

    ],

    'PAGINATION_CONSTANTS' => [
        'KEY_RECORD_PER_PAGE' =>  10,
    ],

    'PAGINATION_CONSTANTS_WEB' => [
        'KEY_RECORD_PER_PAGE'  =>  10,
    ],
];
